---
- hosts: all
  become: true

  tasks:
    - name: running inside the slave server
      shell: echo ls
    - name: remove stopped container
      shell: docker rm -f mini-project
    - name: remove docker images
      shell: docker image rm -f goliakshay357/mini-project:latest

    - name: create docker image
      shell: docker run -d -p 80:80 --name mini-project goliakshay357/mini-project:latest